### ISSUE TITLE
BUG Bestellung anlegen

### ISSUE THREAD

**Issue by Andreas1090** [Burgomehl/ABAP#14]
Angelegte BEstellungen werden zwar in die Tabelle gespeichert aber nicht im Baum angezeigt. 
Außerdem finde ich die Kombination mit Bestellpositionen nicht gut. Ich würde wenn das möglich ist das komplett rausmachen und alles über den Baum? Geht das Stephan? Also bestellungen anlegen im Baum?

**Comment by RoseFlunder** [comment]
Schwierig da der Baum eine View für die Daten benutzt und leere Bestellungen dank des "SAP kann nur inner join bei DDIC views" nicht in der View angezeigt werden können.
Es muss also mindestens eine Bestellposition vorhanden sein, damit die Bestellung im Baum auftaucht.
