### ISSUE TITLE
Bestellungen löschen

### ISSUE THREAD

**Issue by RoseFlunder** [Burgomehl/ABAP#3]
Prüfen ob Bestellpositionen gelöscht werden wenn die Bestellung gelöscht wird.

Wenn eine Bestellung gelöscht wird, sollte diese tatsächlich gelöscht werden? Sprich ID wird wieder frei und benutzbar?
Oder wollen wir mit einem Flag arbeiten für "gelöschte" Bestellungen?
Also die existieren dann weiterhin in der Tabelle, aber beim Select zum Anzeigen würden wie diese dann rausfiltern?
Damit würden wir dann verhindern, dass einmal benutzte Bestellnummern wieder verwendet werden, denn unsere Bestellnummer ist ja unsere ID.
Hier müsste man diskutieren, ob was dann mit den Positionen passiert.

**Comment by Burgomehl** [comment]
Rein theoretisch ist es doch sowieso unsinnig eine Bestellung zu löschen. Wir haben doch ein extra Feld mit (offen,bezahlt,storniert).

**Comment by RoseFlunder** [comment]
Guter Einwand, ist eigentlich nicht logisch.
Aber die Aufgabe sagt:
"Bestellungen anzeigen, anlegen, bearbeiten und löschen".
Sollte man Herrn Schmidt vielleicht mal fragen, ob löschen bei Bestellungen bedeuten könnte, dass diese auf "storniert" gesetzt werden sollten.
Und was soll in dem Fall bei Bestellungen passieren, deren Datum schon in der Vergangenheit liegt?

**Comment by RoseFlunder** [comment]
Hab jetzt einfach die Bestellpositionen mitgelöscht.. who cares
